version: '3.7'

networks:
  itavscovidbot.network:
    name: itavscovidbot.network
    driver: bridge


services:

  db:
    image: mongo:latest
    container_name: itavscovidbot.db
    restart: unless-stopped
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/data/db
    networks:
      - itavscovidbot.network

  db.web:
    depends_on:
      - db
    image: mongo-express:latest
    container_name: itavscovidbot.db.web
    restart: unless-stopped
    env_file:
      - ./db/web/.env
    ports:
      - 8081:8081
    networks:
      - itavscovidbot.network
    
  app:
    depends_on:
      - db
    build:
      context: .
    container_name: itavscovidbot.app
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - itavscovidbot.network
